### ISSUE TITLE
[common] convert

### ISSUE THREAD

**Issue by Alice52** [Alice52/page#3]
## convert list

1. 选中问题
    ```css
    // removed
    ._1Bj6HN3x_0 {
      position: relative;
      -webkit-user-select: none;
         -moz-user-select: none;
          -ms-user-select: none;
              user-select: none;
    }
    ```
2. 跳转问题
    ```js
    <base href=.*?>
    ```
